### ISSUE TITLE
Link color changes navigation background

### ISSUE THREAD

**Issue by theopeek** [jameskoster/highwind#102]
When choosing a different color for links, the background for sub-pages in the hamburger navigation is changed:

![schermafdruk 2015-01-27 10 08 22](https://cloud.githubusercontent.com/assets/6461813/5916022/81f008d8-a60c-11e4-8006-b9fa84a25e12.png)

I am using the theme on wordpress.com.

**Comment by jameskoster** [comment]
The wordpress.com version is different to the .org version. I suggest contacting the team at .com about this.
