### ISSUE TITLE
Override customizer values in a child theme

### ISSUE THREAD

**Issue by bassscape** [jameskoster/highwind#111]
I have a child theme setup for Highwind.
I would like to programatically set new default color values in some of the customizer options.
Is this currently possible with Highwind?

**Comment by jameskoster** [comment]
I'm afraid not, we'd need to add filters to allow this. Not something I have the time to do atm I'm afraid :-(

**Comment by bassscape** [comment]
Fair enough. This isn't really an issue so this should be closed. Thanks for the high quality theme James.
