### ISSUE TITLE
"continue reading" anchors obscured under the nav/menu bar

### ISSUE THREAD

**Issue by iMattPro** [jameskoster/highwind#24]
Great theme. However, when you use the More/Continue Reading feature, if you click on the link, and you are taken to the full blog post page, while the browser does park the page at the correct anchor point, the anchor is at the very top of the browser window, so the first few lines of the post text - picking up where you left off reading - are hidden underneath the menu bar.

**Comment by jameskoster** [comment]
This is because the navigation is fixed in position. Not really sure there's much that can be done about this as the more link/anchor is a part of WordPress core.
