### ISSUE TITLE
James! Help Gravatar is killing me

### ISSUE THREAD

**Issue by Lovesgirl** [jameskoster/highwind#25]
Hi, WP and GitHub newbie.  Have your theme installed ver 1.1.1 but having problems with the gravatar on the home page. I got your code in the documentation for removing the Gravatar but when I do that, it removes it but then the image in the header gets distorted and I can't put the header image in there.  The theme enlarges it and makes it huge.  I can get the header image to look right but only if I leave the gravatar in there. I even tried making a "invisible png" file to replace it. but don't think i did that right either.  I don't know code but I'm good at copy and paste LOL  Would really appreciate your help.  Attached: current.tiff how it appears now (correct if I could get gravatar off)
Please help :)

![current](https://f.cloud.github.com/assets/5882917/1495746/e800065e-47ef-11e3-8e08-ec94a41a4962.jpg)
![templates](https://f.cloud.github.com/assets/5882917/1495747/e9ea09ba-47ef-11e3-9e74-77925b38408e.jpg)
![highwind-template](https://f.cloud.github.com/assets/5882917/1495748/ebe9386c-47ef-11e3-9868-096a682cf9af.jpg)
![functions](https://f.cloud.github.com/assets/5882917/1495749/edb7e986-47ef-11e3-8a93-c11200ebab34.jpg)

**Comment by jameskoster** [comment]
Hey, you've put the snippet inside a comment so it wont work. You need to add it after the */ 

Then you will just need some CSS to increase the height on your .header. Post on the .org forum for support :-)

**Comment by Lovesgirl** [comment]
Fantastic! thanks James :)

On Nov 8, 2013, at 7:03 AM, James Koster wrote:

Hey, you've put the snippet inside a comment so it wont work. You need to add it after the */

Then you will just need some CSS to increase the height on your .header. Post on the .org forum for support :-)
