### ISSUE TITLE
Create Author Comment Styles

### ISSUE THREAD

**Issue by BFTrick** [jameskoster/highwind#28]
The post author's comments should probably look distinct from that of a regular commentator.

I'd be happy to make a PR for this. Any guidelines? Maybe darken the speech bubble by 10% or something like that?

Or, if possible, bring the header color (purple in my case) into the speech bubble - maybe a lightened version or the normal version but just the edges?

![show_me_that_you_re_passionate_about_learning___the_community-4](https://f.cloud.github.com/assets/1065372/1585114/3814bb04-5217-11e3-92aa-d4293af0da4d.png)

**Comment by jameskoster** [comment]
I like the idea of the author comment bubble using the main theme color. Feel free to send a PR. Remember to check the options though and the text will need need to be the color of the content bg color option I guess :-)
