### ISSUE TITLE
woocommerce problem

### ISSUE THREAD

**Issue by cypher288** [jameskoster/highwind#29]
Hi,

I'm having problems when displaying the products and their description. In my web  http://soldiabetis.esy.es/ in shop section if you enter  the product not looks good and if you go into the product, don't charge the product description  appears a white stripe below the header.

I put twenty ten, twenty eleven theme and i don't have any problem, the description product appears.

Thanks.

**Comment by jameskoster** [comment]
I can't see the shop on your site? Please post things like this in support.
