### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by AlGregorios** [jameskoster/highwind#3]
Hi there,

I'm not really good in coding and I really like your theme. I want to have just a one page blog that has a Welcome Content in it then all the post are visible underneath that content. Whole Post not a excerpt. Just like this blog http://rabbitsadvice.com/.

What will I do to make this possible?

**Comment by jameskoster** [comment]
Hi, this is not a support channel. Please post things like this on wordpress.org support forums.

Github is for reporting bugs.

Thanks
