### ISSUE TITLE
Issue: Background color and top menu text color the same

### ISSUE THREAD

**Issue by NikV** [jameskoster/highwind#33]
I cannot use certain color schemes with backgrounds and menus because it appears the top menu text is the same color as the background. So perhaps another setting in the customize area that can edit the top menu text could fix this. This only happens when the background and header color is the same.

**Comment by jameskoster** [comment]
I don't want to add _another_ option for this. I don't think it's necessary. In this (edge) case you can tweak the nav link colour with a little CSS.

**Comment by NikV** [comment]
Alright no problem. I can do that.
