### ISSUE TITLE
author comment styles

### ISSUE THREAD

**Issue by jameskoster** [jameskoster/highwind#37]
# fail http://cl.ly/image/3E3Z0K410U35

links in these comments need different color too

**Comment by BFTrick** [comment]
I noticed this too. :)

I assume you can do something fancy with LESS to make them 10% of the link color or something like that?

**Comment by jameskoster** [comment]
I'll just make the links have the same color as the buttons I think, with an underline.

**Comment by BFTrick** [comment]
:+1:
