### ISSUE TITLE
Issue with Highwind theme after latest upgrade to 1.2.2

### ISSUE THREAD

**Issue by nishikk** [jameskoster/highwind#39]
I upgraded to version 1.2.2 of Highwind theme couple days ago, and I am seeing the following issues: 
- I see the Older posts button replicated twice at the bottom of the blog

![image](https://f.cloud.github.com/assets/6210446/1770021/9c113aa6-677f-11e3-881b-33537259d4aa.png)

I need that black button removed.

I checked to see if there is an customized CSS that could be conflicting with it, but I don't see anything. How do I get rid of this black Older Posts box?
- Another issue I see is at the bottom of the posts, there used to be an icon to indicate the author of the post. Now that icon is no longer there, and it looks like the author name (Nish) is also a tag

![image](https://f.cloud.github.com/assets/6210446/1770059/4b8a8f46-6780-11e3-8275-cf7b9904b0ab.png)

Thanks for the help on this issue.

**Comment by jameskoster** [comment]
Not sure how you updated to 1.2.2 considering the latest version is 1.2.0 ;-)

Can I see a URL? I don't know why you have a duplicate post navigation but it looks like one of them is _not_ coming from highwind. Try disabling all plugins to check for a conflict.

There's no reason the author icon would just randomly disappear that makes no sense at all. Again this is most likely a plugin conflict. If I can get a URL I can confirm this.

**Comment by BFTrick** [comment]
@nishikk I've seen that issue once myself. Are you using the Infinite Scroll module in Jetpack?

I haven't seen the issue more than once so I think it is a caching issue. Once your cache is cleared there should be some CSS to hide the duplicate "older posts" button.

**Comment by nishikk** [comment]
@Jameskoster and @Patrick: I could have sworn it was 1.2.2. I must have
been seeing things. I saw now that the author icon issue seems to have
magically resolved itself.

The Older Posts issue could be because of the Infinite Scroll that Patrick
mentions. I didn't have Infinite Scroll enabled earlier, but with the
upgrade, it seems to have come automatically. How would I disable Infinite
Scroll? I don't want this functionality.

Thanks,

Nishita

**Comment by jameskoster** [comment]
I haven't actually tried JetPack infinite scroll, I use a different plugin. But I'm pretty sure it will just be a case of disabling that module in Jetpack?

If @BFTrick has time he can confirm :-)

**Comment by BFTrick** [comment]
@nishikk yup - you just got into JetPack and then under Infinite Scroll press Learn More followed by Deactivate and that will turn it off. Just tested this myself.

Strange - it shouldn't turn on automatically.

**Comment by nishikk** [comment]
@Patrick: Oh, thanks for that. Yup, it worked fine. I didn't even know
there was an Infinite Scroll option over there.

Thanks again :)

Regards,

Nishita
