### ISSUE TITLE
Random text boldness

### ISSUE THREAD

**Issue by ivycheung** [jameskoster/highwind#44]
I noticed that when you type three periods in a row (...), it modifies the surrounding text into bold and screw up the spacing. I removed my usage of it in another post and the text format is back to normal. (I apparently like to use ... a lot).

I checked the content and it's just standard text with no markup.

![image](https://f.cloud.github.com/assets/637384/1837607/9b0c7a78-7439-11e3-8b43-2513c2c537ff.png)

Thanks.

**Comment by jameskoster** [comment]
Can I see a URL where this is happening to inspect? If there's no &lt;strong&gt; tags being added then it must be a quirk of how your computer is rendering the font. Not sure why using the ellipsis (...) would cause that to happen though.

**Comment by ivycheung** [comment]
http://www.iseevines.com/2013/08/14/review-a-kdrama-take-care-of-the-young-lady-2009/

I tried it at work and across 3 different browsers and it is Chrome that has the problem (I use Chrome at home too). I guess there's not much you can do about it since it is Chrome who is rendering it awkwardly.

Sorry!

**Comment by jameskoster** [comment]
Hmm yeah I don't see the issue in your screenshot on that page myself. There's certainly no tags being inserted that shouldn't be. All I can suggest is changing fonts I'm afraid.
