### ISSUE TITLE
Bullet Point misalignment

### ISSUE THREAD

**Issue by ivycheung** [jameskoster/highwind#45]
(Sorry, another issue :|)

The bullet list aligns to the left edge instead of being indented like it should. I tried to figure out where it was and it was just 

```
ul,
ol {
  padding-left: 0;
}
```

pulled it to the left but that is needed for the widgets to pull left. So uh.

Thanks!

**Comment by jameskoster** [comment]
The bullets are hung intentionally. Read about why [here](http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2) :)

**Comment by ivycheung** [comment]
Thanks for the link! I'll have to modify the theme myself to push it back.
