### ISSUE TITLE
Page title font color not the same as post title font color

### ISSUE THREAD

**Issue by ghost** [jameskoster/highwind#46]
Hi there

Not sure if this is a bug or if it's supposed to be like this, but post titles are the same color as the header block (in my case blue) but the page title color is gray.

I've attached screenshots of both so you can see what I mean.

Thanks,

Ang

http://www.angelagayehorn.com/online-content-writer/

![screen shot 2014-01-03 at 2 34 14 pm](https://f.cloud.github.com/assets/6310977/1839187/ab9fe2dc-7473-11e3-8b44-b8b807db301d.png)
![screen shot 2014-01-03 at 2 34 28 pm](https://f.cloud.github.com/assets/6310977/1839189/b31f0f2e-7473-11e3-9c3c-f41c50c44b91.png)

**Comment by jameskoster** [comment]
That's because post titles are links ;-) If you go to a single post page (http://www.angelagayehorn.com/living-lightly/composting-in-the-city/) you'll see the title is the same color as a page title.

**Comment by ghost** [comment]
Thanks James! :-)
