### ISSUE TITLE
Max Width Applied to inner-wrap Div

### ISSUE THREAD

**Issue by BFTrick** [jameskoster/highwind#56]
It looks like you applied a max width to the `inner-wrap` div. I assume this was intentional? It looks a little weird to me but maybe that's my developer brain.

![james_koster___web_dude_-2](https://f.cloud.github.com/assets/1065372/1969087/736e830e-82ed-11e3-8776-712ba07f9b0a.png)

If this is a bug I'll submit a PR - if not I can make changes in a child theme.

**Comment by jameskoster** [comment]
@BFTrick this is actually a feature :D If the background / content background color options don't match then the header width matches the content width. Make sense?

**Comment by jameskoster** [comment]
@BFTrick Maybe it would make more sense if the nav resized too?

http://cl.ly/image/2q3p2a3k082X

**Comment by BFTrick** [comment]
Making the nav resize would make that look better. :)
