### ISSUE TITLE
Button that opens the Navigation menu on mobiles is invisible 

### ISSUE THREAD

**Issue by alexx4** [jameskoster/highwind#63]
The button that opens the navigation menu is the same colour as the header colour (link colour). This makes it very hard to see. And there's no symbol on the button. So it's just a blank square. This was on an android phone.

**Comment by jameskoster** [comment]
Unfortunately I don't have an android to debug this. There should be an icon though. Do you see the same issue on iOS?

**Comment by alexx4** [comment]
Hey James! :)

Actually, you can see the problem if you use this online simulator: https://www.manymo.com/emulators/82/connect

My site is sevenstorieshigh.com but I've checked and the problem is on other highwind sites.l don't know about iOS - don't have one of them. I guess they have a simulator as well somewhere.

**Comment by alexx4** [comment]
It seems to be just on android.

**Comment by alexx4** [comment]
Hi. I've noticed that the bug appears on my girlfriend's phone, which has a small screen. But it doesn't appear on my galaxy S2, which has quite a large one. Don't know if that's any help. I have also seen the symbols sometimes appear on the buttons (on her phone), but they appear very small. So perhaps something to do with re-sizing?

**Comment by jameskoster** [comment]
Hmm this is really strange. The icon is just a glyph in a font. Can you see other icons, for example in the post meta?

**Comment by alexx4** [comment]
Aha! That's it. All the glyphs have disappeared! There aren't any in the post meta either. Do you know any other sites that are using them? I can check to see it the problem is happening outside of highwind. :)

**Comment by jameskoster** [comment]
The font is http://fontawesome.io/icons/ Maybe there's a quirk in my @font-face implementation.

**Comment by alexx4** [comment]
Well that site displays fine. So maybe.

**Comment by jameskoster** [comment]
Give that commit a try @alexx4. Hard for me to test this I'm afraid.

**Comment by alexx4** [comment]
Im sorry, im a bit new to this. What do i do with that code?

**Comment by skara** [comment]
You may go [here](https://github.com/jameskoster/highwind/tree/release-1-2-4/framework/typefaces), download all the files and replace them within your own installation. Make copies of the original files before !

**Comment by jameskoster** [comment]
Or rather got [here](https://github.com/jameskoster/highwind/tree/release-1-2-4) and click the download zip button over there ->

**Comment by alexx4** [comment]
Hiya, I downloaded the zip. Uploaded it within wordpress (under add new theme), and activated it as a theme.

Unfortunately the problem has not been resolved. I notice on google that other people have had similar problems,and have managed to fix it so hopefully the answer is out there. :)

This guy had the same problem, and came up with a solution don't know it you've tried it...  http://www.hanselman.com/blog/WhyDoMyFontAwesomeIconsShowUpAsBlankSquares.aspx

Thanks :)

**Comment by alexx4** [comment]
This also seems like it might be useful http://stackoverflow.com/questions/11991052/font-awesome-does-not-work-on-android-browser

**Comment by jameskoster** [comment]
The first issue is different. That was just a case of the wrong font being applied to the element.

Which version of the Android browser are you using?

**Comment by alexx4** [comment]
Sorry for slow reply.  On 2.33 (my phone) it works fine. It's version 4.22 that is the problem maker for us.

**Comment by jameskoster** [comment]
Is that the latest?

**Comment by alexx4** [comment]
I don't know, but I found a link which has all the versions in a table:

http://decadecity.net/blog/2013/11/21/android-browser-versions (the table is at the bottom). 

Looks like the last version was 4.3. Then Android started using chrome browser as the stock browser. 

I tried opera mini on my phone, and it also cannot display the glyphs (puts a blank rectangle there instead). Thought it might be easier to debug as it's not just available on android? I now nothing about code, so sorry if that's a silly suggestion. haha

**Comment by skara** [comment]
Looking at http://caniuse.com/fontface it should not work with older versions. So the problem with font-face is known. But i can't test it myself for not having android devices.

It's a decision whether to support older browsers (eg. by using images like other themes -> http://themes.elmastudio.de/ubud/) or make the best of the blank square.

As far as i'm concerned i wouldn't support another elderly browser version (you already do by supporting older IE).

**Comment by jameskoster** [comment]
If 4.3 ships with Chrome (which I assume this works in) I'm probably not going to be able to dedicate time to look into this. Unfortunately, without an Android device it's a real pain for me. I'll leave this open for a while hoping someone submits a fix or sheds some light on this.

**Comment by alexx4** [comment]
Thanks James, I do appreciate you having a look at it, and I really like the theme otherwise.

Skara. Thanks for your advice, appreciate it.

I am going to try and change both your minds though: what about Oprah mini? That's the latest download (and is also available on iPhone.) So it's not elderly at all.

Also the stock-browser for android is still put on some of the latest phones. Turns out not every phone has chrome, just some of them. (like my GF's phone which she brought only three months ago.) So those phones aren't elderly. 

Android has about 80% of the market, add that to other cross-party browsers (like Oprah). And surely this is too many people to rule out. 

There is a fix as well! Which sounds good. It basically detects whether your phone supports the glyphs and, if it doesn't, it loads a different icon or image. Surely this is worth adding to highwind? Why not include these users if it's possible.

http://stackoverflow.com/questions/12312323/how-to-know-if-a-font-font-face-has-already-been-loaded/12316349#12316349

(There are some other methods on that page as well.)
