### ISSUE TITLE
function 'wc_setup_product_data' not found

### ISSUE THREAD

**Issue by corsonr** [jameskoster/highwind#64]
It seems that highwind generates an error with WC2.1:

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wc_setup_product_data' not found or invalid function name in /wp-includes/plugin.php on line 507
```

This error message appears on the frontend and on the backend, and disappears when the page gets refreshed.

**Comment by jameskoster** [comment]
Going to close this pending further investigation. I'm unable to replicate.
