### ISSUE TITLE
Dropdown navigation not working at iPad

### ISSUE THREAD

**Issue by skara** [jameskoster/highwind#65]
Hi

as stated at [wordpress.org](http://wordpress.org/support/topic/ipad-strange-behaviour-with-mobile-nav-vs-regular-nav) the dropdown menu doesn't work as expected at iPad.

Situation to reproduce:
iPad 2, orientation landscape, navigation menu at the top of the site including sub menues

Portrait orientation brings the mobile version of the theme. Landscape orientation brings up the desktop version.
At a computer hovering a navigation menue including sub menues reveals the sub menues. For the iPad (other tablets/touchscreen-devices too?) there's no hover-effect. Clicking an item instantly forwards to the location while it's supposed to open the sub menu.

Solution:
Work around the on-mouse-click-event for touchscreens with desktop version of the theme.
E.g.: I found [this](http://www.prowebdesign.ro/simple-responsive-template/) working at the iPad but aren't able to build it into highwind theme myself.

**Comment by jameskoster** [comment]
hm I think something changed in a recent iOS update. Gonna keep my eye on this as it may be an iOS issue.

**Comment by skara** [comment]
I checked it again.
The former versions of this theme didn't seem to work correctly too (i checked 1.0.1 and 1.2.1).
I've tested a few other themes (eg codium-extend) that worked like a charm but i couldn't fix highwind.
So iOS (7.0.4 here) doesn't seem to be the failure to me.

**Comment by skara** [comment]
I'm not that good at developing php/js/css but following fix worked for me:

```
#navigation .sub-menu {
    display: none;
}

#navigation li.menu-item-has-children:hover > .sub-menu {
    display: block;
}
```

**Comment by jameskoster** [comment]
Thanks, I'll implement this in the next version.
