### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by clodiopulcro** [jameskoster/highwind#66]
Hi, I have a problem with wordpress gallery. For example if i made a gallery with 2 imeges, the images are aligned on the left, the caprion ionstead on the right.
It would be better if they were aligned (maybe center aligned)
http://www.imagebam.com/image/9caf71311950097

Thank you

**Comment by skara** [comment]
If possible give an example url.

**Comment by clodiopulcro** [comment]
http://ricetteintramontabili.altervista.org/amor-pontremolesi
as you can see, image is aligned on the left, caption on center

**Comment by skara** [comment]
You may add following css to your style.css 

```
.gallery img {
    margin-left: auto;
    margin-right: auto;
}
```

And you may better use a [child theme](https://codex.wordpress.org/Child_Themes) for customizations so further updates of highwind-theme doesn't break them.

**Comment by clodiopulcro** [comment]
Thank you. Works great!
