### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by kylemclaren** [jameskoster/highwind#68]
Please help out a WordPress n00b.

I'd like to move the menu items from the left to the right of the nav bar and insert a logo on the left.

I've tried `float: right` on `highwind-navigation` class in my child theme style.css but something is interfering and I can't figure out what...

**Comment by jameskoster** [comment]
Hey, please post support requests like this on wordpress.org forums. Github is strictly for bug reports. Thanks!

**Comment by kylemclaren** [comment]
Well this issue is specific to this theme as something is interfering with `float: right`

Have subsequently switched to another theme and managed to get it.

Thanks.

**Comment by jameskoster** [comment]
Yes but it's specific to a customisation you are making and therefore not a bug ;-)
