### ISSUE TITLE
Weird 500 Product page error

### ISSUE THREAD

**Issue by navjotjsingh** [jameskoster/highwind#73]
This is a very weird issue I am facing. Using a combination of Highwind, Woocommerce and AntiSpam Bee plugin produces a 500 http error on the product page. Taking the theme or the Spam plugin out of the equation takes away the error. I am not sure what is causing this error. Woocommerce, AntiSpam Bee or your theme. Can you please take a look at it? I have posted the same on Woocommerce support forums at wordpress.org as well.

**Comment by jameskoster** [comment]
I'll try and look at this over the weekend. Some more info would be great though, any error logs?
