### ISSUE TITLE
Empty id for navigation-paging

### ISSUE THREAD

**Issue by skara** [jameskoster/highwind#75]
There's always an empty id for content-navigation.

```
<nav role="navigation" id="" class="navigation-paging">
```

(framework/highwind-template.php line 177) reads:

```
function highwind_content_nav( $nav_id )
```

Problem is initial call doesn't contain a variable (includes/theme-action.php line 30).
In function highwind_main_navigation (line 58) the id is set directly.

What was the indention using $nav_id ? What do you wanted it to be ?
Solutions: Declare variable, set id directly too (eg. content-navigation) or drop the id attribute completly?

**Comment by jameskoster** [comment]
Totally missed this. There's no need for the ID, can be dropped.
