### ISSUE TITLE
Images for Testimonials is displaying very large.

### ISSUE THREAD

**Issue by seb86** [jameskoster/highwind#76]
Would it be possible for a little CSS to be applied to support the images that are attached to testimonials under the project. It is currently showing full width and yet both the width and height is showing 50px.

Here is the code that displays the testimonial under the project.

```
<div id="quote-2346" class="quote first last" itemprop="review" itemscope="" itemtype="http://schema.org/Review"><blockquote class="testimonials-text" itemprop="reviewBody"><p>Sébastien was an amazing help to my company. I had some PHP coding that I needed that several developers failed to help with. He was not only able to solve the problem for my client, he did it quickly and under budget.</p>
</blockquote><img width="50" height="50" src="http://www.sebastiendumont.com/wp-content/uploads/2012/12/john-young-125x125.jpg" class="avatar wp-post-image" alt="John Young"> <cite class="author" itemprop="author" itemscope="" itemtype="http://schema.org/Person"><span itemprop="name">John Young</span> <span class="title" itemprop="jobTitle">Shout it Out Design</span><!--/.title-->
 <span class="url"><a href="http://www.shoutitoutdesign.com" itemprop="url">http://www.shoutitoutdesign.com</a></span><!--/.excerpt-->
</cite><!--/.author-->
</div>
```

Plugins used: Testimonials by WooThemes, Project by WooThemes.

I'm not sure if it would be better to be applied to the either plugin or this theme.

Please let me know your thoughts.

Thanks.

Sebastien.

**Comment by jameskoster** [comment]
There are no plans to integrate Highwind with any other plugins at the moment I'm afraid. You'll need to add this to your child theme or via custom css plugin for now.

**Comment by seb86** [comment]
Ok. Thank you for letting me know.
