### ISSUE TITLE
Revert to Unstyled Text When Webfonts are Slow to Load

### ISSUE THREAD

**Issue by BFTrick** [jameskoster/highwind#77]
Hey James,

I noticed that with certain browsers like Opera; a browser will wait for a webfont to be completely loaded before rendering it. That means that if the connection is slow that the user might not see any text on the site for X seconds.

There's some discussion here about potential work arounds: http://stackoverflow.com/questions/8390140/revert-to-unstyled-text-when-web-fonts-are-slow-to-load

On my site only 0.5% of my traffic uses Opera so this to me sounds like overkill. I still thought I'd bring it up. :)

**Comment by jameskoster** [comment]
https://github.com/typekit/webfontloader

I might get time to look into this one day :D

**Comment by OpenCode** [comment]
With Chromium, too!
