### ISSUE TITLE
Change Article Elements Order

### ISSUE THREAD

**Issue by X-Raym** [jameskoster/highwind#78]
Hi !

Thanks for your awesome theme ! :D 
I'm trying to figure out how to customize it, so i have one question :

What if i want to have the metas (of an article) to be in bewteen the title and the content section ? 

Thanks :)

**Comment by skara** [comment]
"_bewteen the title and the content section_" ?
I guess you mean within the head section of the html.
Take a look at [Meta Tags in Wordpress](https://codex.wordpress.org/Meta_Tags_in_WordPress) for this.

**Comment by skara** [comment]
... if you want to insert meta by editing the header.php you better use a [child theme](https://codex.wordpress.org/Child_Themes) ;)

**Comment by X-Raym** [comment]
Thanks :)
In fact it was not the html meta but the article meta (date, modified time, tags...) that i was talking about. Sorry, I didn't explain that very well =/
I just find it !
So it's not in head.php but in content.php :)

**Comment by jameskoster** [comment]
You could also plug the `highwind_post_meta` function to add your own meta.
