### ISSUE TITLE
Add Modified Date

### ISSUE THREAD

**Issue by X-Raym** [jameskoster/highwind#79]
Hi :)
if i want the modified_date to appear next to the post_date on article pages, what is the best option ?
Modify content.php ? add a function in highwind-template.php or something else ?

thanks :)

**Comment by skara** [comment]
Please post support requests like this on wordpress.org forums. Github is strictly for bug reports. Thanks!

PS: It depends on your own knowledge and your needs. You may get better answers at the forum.

**Comment by X-Raym** [comment]
Oh sorry I didn't want to spam you =/
I posted here because it's in the middle between support and feature request :P

See you on wordpress forum !

**Comment by jameskoster** [comment]
This is basically the same as your other issue. I'll close :-)
