### ISSUE TITLE
Issues with photos, header, gravatar

### ISSUE THREAD

**Issue by JonBquist** [jameskoster/highwind#80]
I posted this to the Wordpress forum, as well. All of a sudden, within the past 30 minutes, my site is having issues with the header photo, the gravatar, and multiple photos across the site. Separate issues are visible on different browsers - IExplorer, Chrome, Firefox, etc. I am also still having issues with copmatability on Mac. I have no idea what's going on, and am wondering if something is being modified on your end with the theme? I don't know how that would affect the site if I didn't download anything new. Any help you can provide is appreciated

**Comment by skara** [comment]
Modifying anything here doesn't affect your installation as long as you don't update the theme yourself (and no, there was no update since a few weeks).
your problems aren't from the theme as stated at wp forum.

~~close~~

**Comment by JonBquist** [comment]
Got it - I have no idea what happened, but for about an hour everyhting was messed up. Now it is showing up fine. Thanks for the response
