### ISSUE TITLE
.wp-post-image class is overriding all image widths

### ISSUE THREAD

**Issue by seb86** [jameskoster/highwind#85]
This piece of CSS is overriding all image width values. Can it be removed please? This is a source of many issues I am finding with any image loaded. No matter what size the image is even small, it just blows up full width of the page or container.

`img.wp-post-image { width: 100%; }`

**Comment by jameskoster** [comment]
You can remove it via child theme for now. I'll tweak for the next release.

**Comment by funkatron82** [comment]
This could be changed to `max-width`.  I'm assuming its there to prevent images from getting too big?

**Comment by jameskoster** [comment]
Yup I think that was the intention. Max-width would be more appropriate.
