### ISSUE TITLE
Videos in posts will overflow outside the content area

### ISSUE THREAD

**Issue by funkatron82** [jameskoster/highwind#86]
If you embed a video file in a post and its width is large, it will overflow out of the content area.  I think its related to the fact that `$content_width` isn't set correctly.

**Comment by jameskoster** [comment]
What kind of videos? Youtube embeds? Videos you've uploaded manually?

**Comment by funkatron82** [comment]
Videos uploaded to the server.  By default, videos you upload pr embed are
either their original width or the `$content_width`.

I actually have a question related to this: you have `$content_width` set
to 1089px and the content area is set to 60% of the content wrapper.  Doing
the math, the only way the $content width would be that large is if the
content wrapper was 1800px wide.  Since content width is set so big, it
causes the videos to bleed out of the content area, since they use that
width to display themselves

**Comment by jameskoster** [comment]
I think that was to cater for the full width template :-)

**Comment by funkatron82** [comment]
Hmm... maybe a way to dynamically change the `$content_width` depending on
the template is in order.

**Comment by funkatron82** [comment]
Issue will be fixed in WP 4.0
