### ISSUE TITLE
Navigation Drop Down Not Working

### ISSUE THREAD

**Issue by nbuchan1** [jameskoster/highwind#88]
Hey James,

I just started using your theme for my person site. I love the theme, but I'm just having one problem. The navigation drop down isn't working. My site is natebuchanan.org under the "Travel Hacking" tab, I have three other sub headings that should be showing up. Any thoughts on how I can fix this?

Thanks,

Nate

**Comment by jameskoster** [comment]
Hey, this isn't the place to post for support :-)

The dropdowns work, I'm guessing there's a plugin conflict on your site, please try deactivating.

**Comment by nbuchan1** [comment]
James,

Where should I post for support? All plugins have been deactivated and the drop down is still not working. Thanks. Nate

**Comment by jameskoster** [comment]
The .org forum is the place to go :-)

The reason this isn't working is because your dropdown parents are missing the `menu-item-has-children` class. This was introduced in a fairly recent version of WordPress. You might need to update.

**Comment by nbuchan1** [comment]
Thanks so much! That fixed it. Also, thanks for letting me know where to go next time when I have questions!
