### ISSUE TITLE
Child Theme & Comments Template Issue

### ISSUE THREAD

**Issue by ajcobby23** [jameskoster/highwind#89]
I have a child theme for Highwind that I am using for a client. She uses IntenseDebate for her commenting system. The issue is that we want the commenting system to only show up on posts, not pages. But at present, even when commenting is disabled on pages, IntenseDebate still has an intrusive 'Comments are disabled' box show up, instead of showing nothing/having a clean page.

Their FAQ says to remove this from appearing on pages: "IntenseDebate swaps out the contents of the comments_template() function. Remove that from the page.php file in your theme, and that will remove IntenseDebate from that page."

Unfortunately, the Highwind theme isn't set up like that. There is no comments_template() function on the page.php file. So my question is where and how to I edit this functionality for a child theme?

**Comment by jameskoster** [comment]
Hey,

Create a new function to check `is_page()` then `remove_action( 'highwind_content_bottom',          'highwind_comments_template', 20 );`.
