### ISSUE TITLE
Webkit Issue

### ISSUE THREAD

**Issue by seb86** [jameskoster/highwind#93]
[sumboi_](https://twitter.com/sumobi_) noticed on my site the other day that there is a WebKit issue in Google Chrome and Safari.

Apart from the subtle change in font weight, you can't tell which options is/are selected.

Here are some screenshots taken [from this page](http://t.co/9IjOb0M7pS).

https://cloudup.com/clUFRxTqAwF

https://cloudup.com/clUFRxTqAwF

Works fine in Firefox.

**Comment by jameskoster** [comment]
This is the problem: http://cl.ly/image/473i0V282C2x

**Comment by seb86** [comment]
So I disabled the output of Gravity Forms CSS. The Webkit issue is now gone but the layout of the form is untidy. Would you consider supporting Gravity Forms in your theme?

**Comment by seb86** [comment]
Maybe add this to your CSS.

`.gform_wrapper ul.gfield_checkbox li input[type=checkbox], 
.gform_wrapper ul.gfield_radio li input[type=radio] {
width: 2.2% !important;
}`

**Comment by jameskoster** [comment]
I dont have too much gforms experience (don't even have an active license). So won't be able to add support myself any time soon.

You should use `width: 1em` btw (I think, maybe a bit bigger, don't remember off the top of my head). Using a % width could end badly.

**Comment by seb86** [comment]
Badly for responsive viewing?

1.5em looks good. 1em looked squashed.

**Comment by jameskoster** [comment]
exactly.

**Comment by seb86** [comment]
OK Thank you for your help.
