### ISSUE TITLE
Unable to change background color

### ISSUE THREAD

**Issue by mattzuba** [jameskoster/highwind#98]
Using v1.2.6, I'm unable to save changes to the background color.  I tried changing it first to the same color as the content background to no avail, and then to a completely random color, with the same results.  I checked the custom options in the database and the custom background color doesn't appear to be being saved.  Not too familiar with the customize options of Wordpress themes, but I'll try to dig into it.

**Comment by jameskoster** [comment]
It's definitely working. Perhaps you have made changes to the theme that are preventing this? Or have a plugin installed that is causing conflict?

**Comment by mattzuba** [comment]
Did you actually test it before saying it works and closing this out?  I don't have any plugins enabled at the moment, and this is the only theme installed, with no child theme and no changes to it.

Based on my troubleshooting, this issue was introduced by 6075063d234377e45be55c5baa180cd22760454e.  Reason being is because Wordpress already does some special sanitizing to the background_color setting in [class-wp-customize-manager.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-customize-manager.php#L1043) to remove the hash from the color [in this function](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-customize-manager.php#L1295).

Commenting out [this line](https://github.com/jameskoster/highwind/blob/master/framework/highwind-options.php#L55) fixes the issue for me.

**Comment by jameskoster** [comment]
You were right :-)

**Comment by mattzuba** [comment]
Thanks for the fix. :-)
